### ISSUE TITLE
Alert in betteruptime when platform fails to fetch front page

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#437]
It occurred a couple times when changes were made in admin to rearrange pages, and for different reasons, it broke the page. Given that user have correct permissions, will need an alert when the entire page fails to load, especially homepage. Check in a 5min interval. 

- [ ] BibleKids app
- [ ] BCC Media app
- [ ] BCC Media web
- [ ] BCC Media tvOS

**Comment by andreasgangso** [comment]
Can't do it in any ci e2e tests, because the issue can happen at admin change time.
Can we have a healthcheck endpoint for the app to test itself?
Would be quite a bit simpler than a separate service.

________________________________
Från: Fredrik Vedvik ***@***.***>
Skickat: fredag, juni 16, 2023 9:22 fm
Till: bcc-code/bcc-media-platform ***@***.***>
Kopia: Andreas Gangsø ***@***.***>; Mention ***@***.***>
Ämne: Re: [bcc-code/bcc-media-platform] Alert in betteruptime when platform fails to fetch front page (Issue #437)


What's the best way here @andreasgangso<https://github.com/andreasgangso> ?

Could copy the queries and run them from a service and just ensure that no errors are returned from the API?

Or we'd have to run continuous e2e tests on all the specified platforms, which might be a bit iffy.

**Comment by fredrikved** [comment]
The e2e tests would have to be continuous, not on the CI part.

What is the definition of a healthcheck? Our issue isn't that the API is down, but that there might be a request that fails due to some permissions or lack of implementation. As we're using GraphQL, our requests differ across our platforms, so what works on Web doesn't necessarily work on app. 

I would run a simple cloud run container that runs these startup/frontpage queries as a public user (as that's likely what's going to break) and makes sure nothing returns errors. Would have to update the queries there whenever we update the startup queries on our platform though.

**Comment by andreasgangso** [comment]
> The e2e tests would have to be continuous (run every x minutes), not on the CI part.
> 
> What is the definition of a healthcheck? Our issue isn't that the API is down, but that there might be a request that fails due to some permissions or lack of implementation. As we're using GraphQL, our requests differ across our platforms, so what works on Web doesn't necessarily work on app.
> 
> I would run a simple cloud run container that runs these startup/frontpage queries as a public user (as that's likely what's going to break) and makes sure nothing returns errors. Would have to update the queries there whenever we update the startup queries on our platform though.

A healthcheck indicates the health of the api, and I'd say the api isn't healthy if it's not able to show the frontpage for public users.
Anyway I suggested an endpoint mostly just to simplify the setup instead of having a separate service. The API can send http reqs with graphql queries to itself on localhost.
That would actually give us the power to do a health check on an unreleased revision before releasing it too.. that's outside the scope for this task though
