### ISSUE TITLE
Logs when thumbs fails to load

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#444]
2 ATVs on same network, One works fine one refuses to load thumbs. We should log this and see how many people have issues if we can.

- [x] tvOS
- [ ] Mobile

![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/2b467fc7-7a72-4317-940c-672e0c0d291b)

**Comment by andreasgangso** [comment]
As far as I understand I'm already logging this and there is 1 case the last 3 months, where the user had network issues

**Comment by andreasgangso** [comment]
Woops I actually had a filter on the logs so I didn't see everything.
There's quite a lot of errors related to fetching images. One of the most frequent "errors" being reported.
I think a portion of it is simply from opening the app without internet.

Anyway, I'll do a quick fix by adding a retry here and I'll also start sending accurate logs on when this issue is visible to the users and maybe include network status if I can..

**Comment by andreasgangso** [comment]
Done in https://github.com/bcc-code/bcc-media-app/commit/7991b8ac3769bb530a71998297806a1a57f29c9a
v4.6.4 will retry image loading if it fails and if it still fails it will report to crashlytics (for bcc media only because we cant have crashlytics it on kids) with error message "Image load failed" and the exception attached.
