### ISSUE TITLE
Investigate notification on kids

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#619]

**Comment by andreasgangso** [comment]
From [the COPPA faq](https://www.ftc.gov/business-guidance/resources/complying-coppa-frequently-asked-questions)
Bold added by me:

### 9. I have a child-directed app and want to send push notifications. Do I need to get parental consent?

> The information you collect from the child’s device used to send push notifications is online contact information – it permits you to contact the user – and is therefore personal information under the Rule.
> 
> To the extent the child has specifically requested push notifications, however, you may be able to rely on the “multiple-contact” exception to verifiable parental consent, for which you **must also collect a parent’s online contact information** and **provide parents with direct notice of your information practices** and an **opportunity to opt-out**. See [FAQ I.2.](https://www.ftc.gov/business-guidance/resources/complying-coppa-frequently-asked-questions#I.%20Verifiable%20Parental%20Consent)
> 
> Importantly, in order to fit within this exception, your push notifications must be reasonably related to the content of your app. If you want to combine this online contact information with other personal information collected from the child, you cannot rely on this exception and must provide parents with direct notice and obtain verifiable parental consent prior to sending push notifications to the child.


### Futher explanation from superawesome
https://medium.com/superawesome-engineering/how-to-implement-coppa-compliant-push-notifications-in-your-kids-app-722afe2a2a22

> With this approach, you can ask the child to enable push notifications, so long as:
> 
> 1. You don’t combine any other personal data collected from the child with the push notification, e.g. you can’t personalise the message by including the child’s name, for example, even if that name was collected in compliance with COPPA.
> 
> 2. At the point of requesting the push notification permission (or before) you obtain the parent’s email address. You must then provide the parent with notice that the child has enabled notifications and give the parent a way to opt out. This is called Direct Notice.
> 
> 3. Your push notifications may only contain information about your app and that is relevant to the child’s activities in the app. For example, a notification that new content is available in a channel the child has followed. You may not send marketing messages about other products..
> 

### Sidenote about persistent identifiers
I was a bit unsure about "persistent identifiers" as they are considered personal information under COPPA and so I started worrying the collection of our ids for statistics was illegal, but statistics fall under the ["internal operations" exception](https://www.toyassociation.org/App_Themes/toyassociation_resp/downloads/newsroom/dec19-letter-to-ftc-on-coppa-rule-review.pdf). We just cant collect any more personal data etc.
Under that exception, using firebase crashlytics shouldve been legal since its for debugging, but play store review blocks it anyway. 


### Alternative approach (local notifications only)

Only use local notifications. While the app is open we can tell the app to schedule some messages defined by the server
Local notifications should be exempt from this whole thing because there is no "online contact information" involved.

Local notifications in some children privacy policies:
https://www.arduino.cc/en/privacy-policy/children-privacy-policy
https://www.viacomcbsprivacy.com/en/childrens/feed

But I dont think we can send per-user, like this article might be suggesting: https://sandejain1.medium.com/coppa-and-push-notifications-4bc4da996fda
This whole approach is very likely in violation because the "userId" he sends becomes "online contact information" when he uses it to target specific users like this, and its not exempt because it doesnt fall under "internal operations" mentioned above. In general its clear that "You can’t use the information to contact a specific person" when reading [here](https://www.ftc.gov/business-guidance/resources/childrens-online-privacy-protection-rule-six-step-compliance-plan-your-business): 

Anyway, local notifications has disadvantages:
- needs to be _scheduled_ beforehand while the app is open/backgrounded. This is the major difference from "push", which can be sent without users opening the app: e.g. for new content.
- much less guaranteed delivery ([OS differences, bugs, etc](https://pub.dev/packages/flutter_local_notifications#scheduled-android-notifications))
  <details>
  <summary>Details</summary>
      "Some Android OEMs have their own customised Android OS that can prevent applications from running in the background. Consequently, scheduled notifications may not work when the application is in the background on certain devices (e.g. by Xiaomi, Huawei). If you experience problems like this then this would be the reason why. As it's a restriction imposed by the OS, this is not something that can be resolved by the plugin. Some devices may have setting that lets users control which applications run in the background. The steps for these can vary but it is still up to the users of your application to do given it's a setting on the phone itself. The site https://dontkillmyapp.com/ provides details on how to do this for various devices. It has been reported that Samsung's implementation of Android has imposed a maximum of 500 alarms that can be scheduled via the AlarmManager API and exceptions can occur when going over the limit."
- Probably requires more debugging and dev time
  </details>

### So basically

1. We need the parents email address. We either wait until we add signup, or we prompt for the email when toggling notifications. I have not found a clear explanation of how the email address should be obtained, but it seems a prompt behind the parental gate would be enough.
2. Send email with information that their child enabled notifications and an opt-out link.
3. We need to implement some backend logic for that opt-out link: Delete the installation id from the backend at least.
4. On the app side, we need to handle the opt-out too, otherwise a new id will be generated automatically. Not sure if its ok to let it renew -> detect the renewal -> disable push notifications. To be safe: every launch, before enabling firebase, we can ask the backend if our token exists. If yes, we havent opted out.

**Comment by andreasgangso** [comment]
@mulundapm @fredrikved code review my research here ^

**Comment by fredrikved** [comment]
What's the purpose of the notifications? If it's to encourage activity, wouldn't we violate it by sending targeted device notifications?

And local notifications don't have this restriction?
