### ISSUE TITLE
Investigate missing age for tvos in metabase

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#929]
age is sometimes empty for data coming from bccm-tvos.

deployment is not part of the story point, do not spend more than 2 story points on this!!!

**Comment by kkuepper** [comment]
As far as I understand, the age_group is taken from the users table and tvos is not logging that event.
Theory: tvos never logged the necessary but was able to gather the age since the mobile app did log it. But the user_id on tvos now looks different so that that accidental hack stopped working.

**Comment by andreasgangso** [comment]
> As far as I understand, the age_group is taken from the users table and tvos is not logging that event. npaw probably doesn't have a property for the age. Theory: tvos never logged the necessary but was able to gather the age since the mobile app did log it. But the user_id on tvos now looks different so that that accidental hack stopped working.

huh, the userid shouldnt look different. what do you mean? - how different?

**Comment by andreasgangso** [comment]
I remember seeing that we are sending age group to NPAW _sometimes_, but not always.

**Comment by kkuepper** [comment]
Using `REPLACE(s.user_id, " ", "+")` fixes the change that happened in February when we updated the npaw version.
However, it doesn't fix that for users that don't use mobile, we don't have age information.

**Comment by andreasgangso** [comment]
> Using `REPLACE(s.user_id, " ", "+")` fixes the change that happened in February when we updated the npaw version. However, it doesn't fix that for users that don't use mobile, we don't have age information.

oh noo. npaw needs to fix this

**Comment by andreasgangso** [comment]
> age is sometimes empty for data coming from bccm-tvos.

I forgot that we have public users on tvOS...
My fix in 4.2.9 is working.
Look at this from npaw_playback_sessions filtered on 4.2.9:

![Image](https://github.com/bcc-code/bcc-media-platform/assets/727125/1deff199-aa39-4a38-8db1-b02e156e2910)

but there are two weird things here.
1. 65+ becomes "65 " because npaw bug affects this too :( I'll see if updating npaw helps.
2. the "npaw playback sessions extended view" maps a lot more rows to "empty". The total count is the same, but something is wrong with that query.

![Image](https://github.com/bcc-code/bcc-media-platform/assets/727125/480d0f3d-c6cd-4526-8b7b-7e38a5010125)

**Comment by andreasgangso** [comment]
Npaw needs to fix their encoding issues so that "+" doesnt become " ".

We can make a new issue for next sprint to follow up, 0 points.
